### ISSUE TITLE
general comments for improvement to website

### ISSUE THREAD

**Issue by tavareshugo** [AndreaPaterlini/Plasmodesmata_dist_wall#1]
Hi @AndreaPaterlini,

Really thorough instructions, it's great! :smiley: 

Some general comments:

**Welcome** page:

- break text into some sections, namely "Acknowledgements" and "Citation/License". 
- Add a license to your repository ([instuctions](https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository))
- Include an outline of the sections. The section names are very general and hard to understand what they are about. My suggestion would be to list them in the welcome page, with the link to the section and perhaps the main question being addressed in that section. 
- Replace "if you are interested in version control" by "if you are interested in the source code"
- Instead of email, consider "report bugs by [opening a new issue](https://github.com/AndreaPaterlini/Plasmodesmata_dist_wall/issues) on our repository". If you use GitHub it's easier to keep track of what you need to do, and other users can also see what issues are open.
- Thanks for thanking me :smile: . Maybe turn my name into a link to my github: https://github.com/tavareshugo
- Make a section called "Setup" (or even a separate page) with all the software installation instructions. Then remove those instructions from the middle of the other pages. Make sure you include all the packages needed as well (more comments on package usage below). And which versions were used for your analysis. 

**Preliminary Steps:**

- Between each heading of your pages you have "We will now XXXX in the next section" as a link to the section that's just immediately there. I would remove those phrases completely (they seem redundant and are just linking to what's there already). 
- You mention the MIB tutorials, consider turning that into a link.
- typo: "next to **the**" should be "next to **them**"

**Distributions**

- This section's name is quite generic. Can you think of something slightly more informative? "Surface distributions"?
- I would redefine the question as: "are plasmodesmata spread homogeneously across the cell wall?". The word "bias" is maybe ambiguous, it made me think of are they biased towards the bottom or top, left or right. 

Regarding R code, several comments that are not exclusive to this section:

- Do not do `setwd()`, as it's not reproducible on someone else's machine. Just mention that the working directory is assumed to be the folder with the data and so paths are given relative to that. 
- Generally try to be consistent in the code. You use `read.csv` and then `read_csv` (from `tidyverse`). Use the latter only, and be consistent throughout. 
- You do not need to use `data.table` (usually it's good to avoid mixing `data.table` and `tidyverse` due to function conflicts). To rename columns you used `data.table::setnames()`, use `dplyr::rename()` instead.
- Do not use `subset()` to select columns (the purpose of that function is to filter rows actually). Using `select()` would be more standard here.
- Lines [141](https://github.com/AndreaPaterlini/Plasmodesmata_dist_wall/blob/2e4a7fc37f34fdce6f7485e37cd5a4d1476f4203/distributions.Rmd#L141) and [385](https://github.com/AndreaPaterlini/Plasmodesmata_dist_wall/blob/2e4a7fc37f34fdce6f7485e37cd5a4d1476f4203/distributions.Rmd#L385) are a bit confusing... If I see what you're trying to do, I think this might work: `gsub("_.*", "", distances_cell$DatasetFilename)` (substitute underscore followed by any character any number of times, with nothing). This should also be much faster that your `sapply` solution. 
- Also `stringr` is loaded with `tidyverse`, no need to have it there.
- More generally, load all the packages at the top of the section (because as a best practice we tend to load all the packages at the top of the analysis script) 
- Consider moving some of the code comments to the main text. For example `# please note that there might be slight differences compared to the figure in the paper since different spatial controls were employed for the two. There are no conceptual differences.` could be in the text.
- In line [233](https://github.com/AndreaPaterlini/Plasmodesmata_dist_wall/blob/2e4a7fc37f34fdce6f7485e37cd5a4d1476f4203/distributions.Rmd#L233) you don't need to explicitly call `purrr::map()`, the `purrr` library is loaded with `tidyverse`, so you can just do `map()`.
- Consider setting your ggplot2 theme in a hidden chunk, so you don't need to repeat [all these lines of code](https://github.com/AndreaPaterlini/Plasmodesmata_dist_wall/blob/2e4a7fc37f34fdce6f7485e37cd5a4d1476f4203/distributions.Rmd#L248-L254) all the time. You can use the following, which will set the theme for the rest of the session: 

```r
theme_set(
  theme_bw() + 
    theme(axis.title.x = element_text(size = 12), 
          axis.title.y = element_text(size = 12), 
          axis.text.x = element_text(size = 12), 
          axis.text.y = element_text(size = 12),
          strip.text.x = element_text(size = 6),
          legend.text=element_text(size=12),
          legend.title = element_text(size=12))  
)
```

Hope this is useful!

**Comment by AndreaPaterlini** [comment]
All issues addressed. 
Thank you very much for the feedback Hugo!
